replicaCount: 1

image:
  repository: slab-backend
  pullPolicy: IfNotPresent
  tag: "prod"

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: true
  automount: true

frontend:
  enabled: true
  image:
    repository: slab-ai-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

mongodb:
  enabled: true

# Secrets Configuration
secrets:
  mongodb:
    uri: "mongodb://slab-ai-slab-ai-chart-mongodb:27017/slabai"
  nodeEnv: "production"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: slab-ai.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
