replicaCount: 1

image:
  repository: slab-backend  # ✅ Your backend image
  pullPolicy: IfNotPresent
  tag: "prod"  # ✅ Specific tag

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

# MongoDB connection configuration
mongodb:
  uri: "mongodb://mongodb.slab-ai.svc.cluster.local:27017"  # ✅ Added MongoDB URI

service:
  type: ClusterIP
  port: 3000  # ✅ Changed to match backend port

ingress:
  enabled: true  # ✅ Enable ingress
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

# Health checks on correct port
livenessProbe:
  httpGet:
    path: /health  # ✅ Changed to health endpoint
    port: 3000     # ✅ Correct port

readinessProbe:
  httpGet:
    path: /health  # ✅ Changed to health endpoint  
    port: 3000     # ✅ Correct port

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

httpRoute:
  enabled: false  # Set to true only if you are using Gateway API
  annotations: {}
  parentRefs:
    - name: gateway
  hostnames:
    - chart-example.local
