FROM node:18-alpine
WORKDIR /app

# First copy ONLY package files
COPY backend/package*.json ./

# Install dependencies (including devDependencies)
RUN npm install

# Then copy the rest of the app
COPY backend/ .

CMD ["node", "server.js"]
