apiVersion: v1
kind: Service
metadata:
  name: {{ include "slab-ai-chart.fullname" . }}-mongodb
  labels:
    {{- include "slab-ai-chart.labels" . | nindent 4 }}
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
    {{- include "slab-ai-chart.selectorLabels" . | nindent 4 }}
