apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slab-ai-chart.fullname" . }}-mongodb-pvc
  labels:
    {{- include "slab-ai-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
