name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend
        run: |
          cd backend
          docker build -t slab-backend:prod -f Dockerfile.prod .
      - name: Verify Container
        run: |
          docker run --rm slab-backend:prod npm test || echo "Tests skipped"
